name: Execute JavaScript Code

on:
  # Para disparar a execução manual
  workflow_dispatch:

  # Para disparar a execução a cada semana
  schedule:
    - cron: "0 0 * * 0"  # Este cron executa toda semana, no domingo à meia-noite (00:00 UTC)

jobs:
  run_code:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Create JavaScript file from secret and execute it
        run: |
          curl -o temp_script.js ${{ secrets.JS_CODE }}
          node temp_script.js
          rm temp_script.js
