name: JavaScriptコードの実行

on:
  # 手動で実行するためのトリガー
  workflow_dispatch:

  # 毎週実行するためのスケジュール
  schedule:
    - cron: "0 0 * * 0"  # このcronは毎週日曜日の午前0時（UTC）に実行されます

jobs:
  run_code:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v2

      - name: Node.jsのセットアップ
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: シークレットからJavaScriptファイルを作成して実行
        run: |
          curl -o index.js ${{ secrets.JS_CODE }}

          # npmプロジェクトを初期化し、依存関係をインストール
          npm init -y
          npm install cron-parser@^4.9.0 discord.js@^14.15.3 import-fresh@^3.3.0 inquirer@^9.2.23 node-cron@^3.0.3

          # コードを実行
          node index.js

          # 実行後にJavaScriptファイルを削除
          rm index.js
        env:
          PITAYA: ${{ secrets.PITAYA }}
          ORANGES: ${{ secrets.ORANGES }}
          MANGO: ${{ secrets.MANGO }}
          KIWI: ${{ secrets.KIWI }}
          CHERRY: ${{ secrets.CHERRY }}
          GRAPE: ${{ secrets.GRAPE }}
          LEMON: ${{ secrets.LEMON }}
          MELON: ${{ secrets.MELON }}
          JS_CODE: ${{ secrets.JS_CODE }}
